resources:
  jobs:
    train_model:
      name: ngm-train-model
      tasks:
        - task_key: train
          spark_python_task:
            python_file: /Workspace/Bundles/ngm_mlops/src/pipelines/train.py
            parameters:
              - churn
