name: train_job
tasks:
  - task_key: train_churn
    python_wheel_task:
      package_name: ngm_mlops
      entry_point: ngm-train
      parameters: ["--model", "churn", "--env", "${var:environment}", "--git_sha", "${var:git_sha}"]
    new_cluster:
      spark_version: "13.3.x-scala2.12"
      node_type_id: "i3.xlarge"
      num_workers: 2
    timeout_seconds: 3600

  - task_key: train_fraud
    python_wheel_task:
      package_name: ngm_mlops
      entry_point: ngm-train
      parameters: ["--model", "fraud", "--env", "${var:environment}", "--git_sha", "${var:git_sha}"]
    new_cluster:
      spark_version: "13.3.x-scala2.12"
      node_type_id: "i3.xlarge"
      num_workers: 2
    timeout_seconds: 3600
    depends_on:
      - task_key: train_churn

schedule:
  quartz_cron_expression: "0 0 0 * * ?"
  timezone_id: "UTC"
  pause_status: UNPAUSED